### PR TITLE
Add fixes for PHP 7.2 / 64 bit systems.

### PR DESCRIPTION
**Pull request by GarlickMD**
See CHANGELOG.md for full details.

### CODE REVIEW

**Comment by Dormilich** [comment]
I'm not very happy with changing object names in the 1.x branches esp. since 2.0 is coming (it also depends a bit on the proceeding of the APNIC web service). 

Additionally the IP end num check is incorrect (it would exclude `255.255.255.255`).

**Comment by GarlickMD** [comment]
Many thanks for your feedback. Good catch on the IP end num check. I've corrected that and adjusted the new unit test I added to test for that edge case.

Re: changing the base class object name ... v1.x doesn't work as of PHP 7.2 as Object became a reserved word from that version. So anyone that is regularly patching PHP  is going to lose access to this package, which is a shame.

If you really are against modifying the base object class name as suggested, guess I'll have to use my fork until v2 is available. Perhaps you could let me know whether I will definitely need to do this?

**Comment by Dormilich** [comment]
> v1.x doesn't work as of PHP 7.2 as Object became a reserved word from that version.

I am aware of that (hence the restriction of the PHP version).

> If you really are against modifying the base object class name as suggested

That's more or less a design decision, if it is "safe" to rename (as in no-one uses the object besides the library). And since I'm not the most experienced coder in that regard, I'm somewhat hesitant making that decision (for either option).

> I've corrected that and adjusted the new unit test I added to test for that edge case.

The whole method needs a rewrite anyways since there is also one other major issue (`198.51.100.42/25` currently results in the wrong range).

I think it's better to split this PR, one just for the renaming and another one for the 32bit issues.

PS. Are you interested helping out with v2? So far the object definitions are ready. Cf. [dormilich/rpsl](https://github.com/Dormilich/rpsl) and [dormilich/ripe](https://github.com/Dormilich/ripe) and I'll soon start with the web service [dormilich/ripe-client](https://github.com/Dormilich/ripe-client) since I'm tired waiting for info from APNIC.

**Comment by GarlickMD** [comment]
>if it is "safe" to rename (as in no-one uses the object besides the library)

It would be a curious implementation that used your v1.x base object, but it is a fair point ... ok. I'll look at splitting out the 64 bit fixes shortly.

>PS. Are you interested helping out with v2?

I don't have lots of time at the moment, but I'll keep an eye on progress. If I find time to contribute I'll give you a shout.

**Comment by Dormilich** [comment]
I'll ask some colleagues for help with the 32bit issues, so I'm going to fix that in the 1.0 branch before tackling the PHP 7.2 issue.

**Comment by GarlickMD** [comment]
OK, no worries. Might be worth considering a v2.0.0 that is basically v1.0.6 with the PHP 7.2 fixes as proposed in my pull request (I can split out the 32 bit fixes, that's not an issue).  Then making your new package v3.0.0.

I suggest the new major version as this will cover you if anyone is using your base object...

**Comment by Dormilich** [comment]
Then I'm closing this request and we proceed as discussed.

**Comment by GarlickMD** [comment]
Sure. I'll add the 32 bit fixes shortly.

Do you also want me to resubmit the PHP 7.2 fixes as a potential update to v2.0.0 as suggested in my last post?

**Comment by Dormilich** [comment]
Since that's merely renaming that's not hard to implement myself (plus I need to add the tags for composer as well).

**Comment by GarlickMD** [comment]
No problem. Thanks.

**Pull request closed without merging**
